### ISSUE TITLE
bug: sigsegv for MULTI_STEP check wthout specifying runtime_id

### ISSUE THREAD

**Issue by av** [checkly/terraform-provider-checkly#284]
### Terraform version

1.2.8

### Provider version

1.7.3

### Steps to reproduce

1. In the Checkly account settings, set the default runtime to `2023.09`
2. Specify the MULTI_STEP check resource:
```hcl
 resource "checkly_check" "e2e-shopping" {
    name                      = "Shopping Flow"
    type                      = "MULTI_STEP"
    activated                 = true
    should_fail               = false
    frequency                 = 1
    use_global_alert_settings = true
    locations = [
      "us-west-1",
      "eu-central-1"
    ]
  
    script = file("${path.module}/scripts/shopping.js")
}
```
3. Run `terraform apply`

### What is expected?

One of:
- Check is provisioned with minimal supported runtime for `MULTI_STEP`
- An error message is thrown requesting to specify the runtime compatible with the `MULTI_STEP`

### What is actually happening?

An error is thrown by plugin:
```bash
Stack trace from the terraform-provider-checkly_v1.7.3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac9e09]

goroutine 78 [running]:
github.com/checkly/terraform-provider-checkly/checkly.resourceCheckCreate(0x0?, {0xc44580?, 0xc0004805a0})
        github.com/checkly/terraform-provider-checkly/checkly/resource_check.go:516 +0x229
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd7b640?, {0xd7b640?, 0xc0003fc330?}, 0xd?, {0xc44580?, 0xc0004805a0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:330 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003d3500, {0xd7b640, 0xc0003fc330}, 0xc0003ac1a0, 0xc0003bce00, {0xc44580, 0xc0004805a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002ad1b8, {0xd7b598?, 0xc0003ee200?}, 0xc00024b810)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002fc460, {0xd7b640?, 0xc000339a70?}, 0xc000572e70)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc22100?, 0xc0002fc460}, {0xd7b640, 0xc000339a70}, 0xc000572e00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00040e000, {0xd7e2e0, 0xc000115860}, 0xc00036be60, 0xc0003f9a40, 0x120cb20, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc00040e000, {0xd7e2e0, 0xc000115860}, 0xc00036be60, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
```

**Comment by clample** [comment]
Hi @av,

Thank you for reporting this issue and I'm sorry that you ran into this.

This sigsegv should be fixed now in the Checkly Terraform Provider version `1.7.6`. If you don't specify a runtime ID, no validation will occur now and the check will be created using your account's default runtime (configured [here in the account settings](https://app.checklyhq.com/settings/account/runtimes)).

Multi-step checks are only currently supported on the latest runtime (`2023.09`), though, so I would also recommend explicitly adding `runtime_id = "2023.09"` to any multi-step checks that you create.

**Comment by clample** [comment]
I'll go ahead and close this issue, but please feel free to re-open the issue or let us know if you have any questions.
