### ISSUE TITLE
bug: Terraform Apply failing on creating checkly check

### ISSUE THREAD

**Issue by vinayvennela** [checkly/terraform-provider-checkly#287]
### Terraform version

1.1.7

### Provider version

1.7.5

### Steps to reproduce

Trying to create checkly check, which worked till yesterday. Now I am not able to create checkly check using below snippet.

resource "checkly_check" "synthetic_check" {
  count     = var.enable_checkly ? 1 : 0
  activated = true
  frequency = var.check_frequency
  name      = var.service_name
  type      = "MULTI_STEP"

  locations    = var.checkly_locations
  run_parallel = true

  script = data.template_file.checkly_synthetics_sli.rendered
}

### What is expected?

A Check should be successfully created

### What is actually happening?

Terraform apply fails with below error trace

```
╷
│ Error: Plugin did not respond
│ 
│   with module.synthetic_test.checkly_check.synthetic_check[0],
│   on .terraform/modules/synthetic_test/checkly.tf line 1, in resource "checkly_check" "synthetic_check":
│    1: resource "checkly_check" "synthetic_check" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Releasing state lock. This may take a few moments...
Stack trace from the terraform-provider-checkly_v1.7.5 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaca069]
goroutine 10 [running]:
github.com/checkly/terraform-provider-checkly/checkly.resourceCheckCreate(0x0?, {0xc44720?, 0xc000082960})
	github.com/checkly/terraform-provider-checkly/checkly/resource_check.go:5[37](https://github.com/getndazn/sre-dazn-status-page/actions/runs/7989369744/job/21856616659#step:14:38) +0x229
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd7b9e0?, {0xd7b9e0?, 0xc0004ec450?}, 0xd?, {0xc44720?, 0xc000082960?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:330 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00014b340, {0xd7b9e0, 0xc0004ec450}, 0xc0000bc000, 0xc000099d00, {0xc44720, 0xc000082960})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002e0348, {0xd7b9[38](https://github.com/getndazn/sre-dazn-status-page/actions/runs/7989369744/job/21856616659#step:14:39)?, 0xc000419140?}, 0xc0002092c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00024d040, {0xd7b9e0?, 0xc0002df890?}, 0xc0004962a0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc222a0?, 0xc00024d0[40](https://github.com/getndazn/sre-dazn-status-page/actions/runs/7989369744/job/21856616659#step:14:41)}, {0xd7b9e0, 0xc0002df890}, 0xc000[49](https://github.com/getndazn/sre-dazn-status-page/actions/runs/7989369744/job/21856616659#step:14:50)6230, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00025a1e0, {0xd7e680, 0xc00038c1a0}, 0xc000132120, 0xc0002df5f0, 0x120db20, 0x0)
	google.golang.org/grpc@v1.[51](https://github.com/getndazn/sre-dazn-status-page/actions/runs/7989369744/job/21856616659#step:14:52).0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc00025a1e0, {0xd7e680, 0xc00038c1a0}, 0xc000132120, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:9[63](https://github.com/getndazn/sre-dazn-status-page/actions/runs/7989369744/job/21856616659#step:14:64) +0x28a
Error: The terraform-provider-checkly_v1.7.5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by clample** [comment]
Hi @vinayvennela, thank you for reporting this issue and I'm sorry that you ran into this.

I was able to reproduce this issue. We'll start looking into a fix now.

**Comment by clample** [comment]
Hi @vinayvennela ,

This issue should be fixed now in the Checkly Terraform Provider version `1.7.6`. Multi-step checks are only supported on runtime `2023.09`, though, so I would also recommend adding `runtime_id = "2023.09"` to any multi-step checks that you create.

Thank you again for reporting this issue.

**Comment by vinayvennela** [comment]
@clample A bit unclear on the validation for runtime_id. Our account's default runtime is "2023.09" so as per your explanation there shouldn't be an issue. Isn't it?

**Comment by clample** [comment]
Hi @vinayvennela, I'm sorry for any confusion. Since your account's default runtime is 2023.09 everything should work smoothly. Is everything running ok now with the new Checkly Terraform provider 1.7.6?

**Comment by vinayvennela** [comment]
Yes confirmed 1.7.6 works without any issues. Thanks!
